### PR TITLE
hybris-18.1: Add 32-bit vs 64-bit codec compatibility patches

### PR DESCRIPTION
**Pull request by mlehtima**
Rebase patches on top of latest lineage-18.1.

Change-Id: I557af3ad07fc051567b2e8e3ba8764b2303713c0

### CODE REVIEW

**Comment by Verevka** [comment]
Work perfect! Test: Poco X3 Pro (Hybris18.1)

**Review by Thaodan — CHANGES_REQUESTED** [review]
Can you add the original PR of those patches for context or add some context otherwise?

Also why is this patch only added to this branch? I assume it affects potentially all android versions.

**Comment by mlehtima** [comment]
> Can you add the original PR of those patches for context or add some context otherwise?
> 
> Also why is this patch only added to this branch? I assume it affects potentially all android versions.

These patches are in the hybris-16.0 and hybris-17.1 branches but were accidentally left out from 18.1. For sony devices these patches are in droid-src.

**Comment by Thaodan** [comment]
> > Can you add the original PR of those patches for context or add some
> > context otherwise?
> > 
> > Also why is this patch only added to this branch? I assume it affects
> > potentially all android versions.
> These patches are in the hybris-16.0 and hybris-17.1 branches but were
> accidentally left out from 18.1. For sony devices these patches are in
> droid-src.

Do builds for Lineage OS based ports use those binaries differently? For AOSP 
those come from /system without Hybris patches.
If this is the case for Lineage too then the patch doesn't belong here I 
think.

**Comment by mlehtima** [comment]
> Do builds for Lineage OS based ports use those binaries differently? For AOSP those come from /system without Hybris patches. If this is the case for Lineage too then the patch doesn't belong here I think.

Only reason why these are in hybris-patches is that we don't build system image for lineage based ports. This is unnecessary amount of discussion for a trivial adding of existing patches to a branch.

**Comment by krnlyng** [comment]
wondering if we should consider dropping the "index" lines from the diff too. those are git specific afaik

**Review by krnlyng — APPROVED** [review]

**Comment by Thaodan** [comment]
> wondering if we should consider dropping the "index" lines from the diff too. those are git specific afaik

We use git am to apply and the nullexport  is the easier way to deal with those.

**Comment by Thaodan** [comment]
> > Do builds for Lineage OS based ports use those binaries differently? For AOSP those come from /system without Hybris patches. If this is the case for Lineage too then the patch doesn't belong here I think.
> 
> Only reason why these are in hybris-patches is that we don't build system image for lineage based ports. This is unnecessary amount of discussion for a trivial adding of existing patches to a branch.

Ah I assumed those parts are taken out of /system for both.

**Review by Thaodan — APPROVED** [review]

**Review by Thaodan — CHANGES_REQUESTED** [review]
Please generate the patches with `git format-patch --no-numbered --zero-commit --no-signature --full-index`

**Comment by mlehtima** [comment]
> Please generate the patches with `git format-patch --no-numbered --zero-commit --no-signature --full-index`

That is how these were exported

**Review by Thaodan — APPROVED** [review]

**Comment by Thaodan** [comment]
> > Please generate the patches with `git format-patch --no-numbered --zero-commit --no-signature --full-index`
> 
> That is how these were exported

Sorry mixed something up, approved.

**Pull request merged**
