### PR TITLE
hybris-patches: Remove /dev/cg2_bpf cgroup device.

### PR DESCRIPTION
**Pull request by mkosola**
Systemd v238 mixes cgroup permissions if something else is changing permissions of cgroup mounted devices. This cg2_bpf device is used by netd and it is not running in Sailfish OS.

### CODE REVIEW

**Comment by izh1979** [comment]
Why 42 files are changed?

**Comment by mkosola** [comment]
> Why 42 files are changed?

Well it is patch count increase. Maybe we should remove those patch counts so we don't always need to modify each patch.

**Comment by izh1979** [comment]
I would drop the count (may be not necessary in this MR). It would make things simpler. Especially because typically patch-sets are consisting of the patches related to some particular issue/task. And these patches are different. (If we don't count as "Run SFOS on a device" as a single task.)

**Comment by izh1979** [comment]
Otherwise, LGTM.

**Review by krnlyng — APPROVED** [review]

**Comment by mkosola** [comment]
Added two commits. The first modify patches with `git format-patch -N --zero-commit` and second one add new patch.

**Review by sledges — APPROVED** [review]

**Pull request merged**
