### PR TITLE
hybris-patches: rebase on top of android-10.0.0_r1

### PR DESCRIPTION
**Pull request by Thaodan**

### CODE REVIEW

**Comment by mlehtima** [comment]
The hybris-sony-aosp-pie branch is as the name says for Android 9, if we want Android 10 support then we add a new branch.

**Comment by Thaodan** [comment]
Ah oversaw that. Can have another branch to work on that here or how should I push that?

**Comment by Thaodan** [comment]
Please look at the original header. I set the opengl slot to 5 because it was the only one didn't used by hybris systems. This is my first time doing this so some input from @krnlyng  or someelse would be helpful.

**Comment by Umeaboy** [comment]
Ping!
Any news to this work?
I'm trying to build Sailfish for Samsung Galaxy S10 Plus which uses Android Q.

**Comment by sailinggalaxians** [comment]
Ping again!
Is this not needed anymore?

**Comment by Thaodan** [comment]
It is still needed but belongs in a separate branch as @mlehtima pointed out. All in all this just one piece of the puzzle for a android 10 based adaption.

**Comment by sledges** [comment]
> It is still needed but belongs in a separate branch as @mlehtima pointed out. All in all this just one piece of the puzzle for a android 10 based adaption.

Branch adjusted.

**Comment by Umeaboy** [comment]
I see that Sony uses android-10.0.0_r41 to build AOSP. What happens on 40 revisions?

**Comment by Thaodan** [comment]
Read the commit history..

**Review by sledges — APPROVED** [review]
Thanks for your contrib.

**Pull request merged**
